# Generated by Django 2.1.5 on 2019-01-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.TextField(max_length=1000000)),
                ('nom', models.TextField(max_length=45)),
                ('post_nom', models.TextField(max_length=45)),
                ('pre_nom', models.TextField(max_length=45)),
            ],
            options={
                'verbose_name': 'enseignant',
                'ordering': ['nom'],
            },
        ),
    ]
