# Generated by Django 2.1.5 on 2019-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['titre'], 'verbose_name': 'livre'},
        ),
        migrations.RemoveField(
            model_name='livre',
            name='finger',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='post_nom',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='pre_nom',
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='...', max_length=45),
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.CharField(default='...', max_length=45),
        ),
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.CharField(default='...', max_length=45),
        ),
        migrations.AddField(
            model_name='livre',
            name='livre',
            field=models.CharField(default='...', max_length=45),
        ),
        migrations.AddField(
            model_name='livre',
            name='titre',
            field=models.CharField(default='...', max_length=45),
        ),
    ]
