# Generated by Django 2.1.5 on 2019-01-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190121_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Categorie'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='livre',
            name='livre',
            field=models.FileField(upload_to=''),
        ),
    ]
