# Generated by Django 2.1.5 on 2019-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190124_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='resume',
            field=models.TextField(default='...'),
        ),
    ]
