# Generated by Django 2.1.5 on 2019-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_livre_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
