# Generated by Django 2.1.5 on 2019-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_livre_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/categories_cover'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/books_covers/'),
        ),
    ]
